---
apiVersion: v1
kind: ConfigMap
metadata:
 name: payment-config
 namespace: roboshop
data:
 CART_HOST: "cart:80"
 USER_HOST: "user"
 AMQP_HOST: "rabbitmq"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    name: payment
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: payment
      tier: app
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 1 # we asked for 10 and we are ok if 9 pods are available at the time of upgrade.
     maxSurge: 1 # we asked for 10 and we are ok if 11 pods are running at the time of upgrade.
  template:
    metadata:
      labels:
        name: payment
        tier: app
    spec:
      containers:
      - name: payment
        imagePullPolicy: Always
        image: gopalareddy/payment:k8
        envFrom:
        - configMapRef:
            name: payment-config
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: payment
 namespace: roboshop
spec:
 selector:
  server: payment
  tier: app
 ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
 