---
apiVersion: v1
kind: ConfigMap
metadata:
 name: cart-config
 namespace: roboshop
data:
 REDIS_HOST: "redis"
 CATALOGUE_HOST: "http://catalogue"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    name: cart
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cart
      tier: app
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 1 # we asked for 10 and we are ok if 9 pods are available at the time of upgrade.
     maxSurge: 1 # we asked for 10 and we are ok if 11 pods are running at the time of upgrade.
  template:
    metadata:
      labels:
        name: cart
        tier: app
    spec:
      containers:
      - name: cart
        imagePullPolicy: Always
        image: gopalareddy/cart:k8
        envFrom:
        - configMapRef:
            name: cart-config
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
 name: cart
 namespace: roboshop
spec:
 selector:
  server: cart
  tier: app
 ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
 